use mentorMe_db;

INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Ester", "Garcia", "egarcia@gmail.com", "qwerty", "http://www.778home.com/wp-content/uploads/2016/04/CStudio_2196-122-318x180.jpg", "Irvine", "CA", "92570", "aboutMe", "web development", "free", "photoshop", "paid", "skateboarding", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Louis", "Smith", "lsmith@gmail.com", "qwerty", "http://thebikinibuilders.com/wp-content/uploads/2017/07/kettlebell-bodybuilding-workoutt-320x180.jpg", "Newport", "CA", "92571", "aboutMe", "surfing", "free", "soccer", "paid", "javascript", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Rhonda", "Lee", "rlee@gmail.com", "qwerty", "http://media.womanista.com/2017/01/overweight-exercise-52572-320x180.jpg", "Orange", "CA", "92572", "aboutMe", "guitar", "free", "basketball", "paid", "exercise", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Beatrice", "Douglas", "bdouglas@gmail.com", "qwerty", "http://media.womanista.com/2017/01/woman-in-pool-52444-320x180.jpg", "Westminster", "CA", "92573", "aboutMe", "drums", "free", "trading", "paid", "options", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Alabama", "Nicholas", "anicholas@gmail.com", "qwerty", "http://s3.india.com/wp-content/uploads/2017/08/Sapna-320x180.jpg", "Huntington", "CA", "92574", "aboutMe", "spanish", "free", "math",  "paid", "volleyball", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Roger", "Brown", "rbrown@gmail.com", "qwerty", "http://miseenforme.ca/s/charleslamontagne/photo-4/homme%20gras.jpeg", "Brea", "CA", "92575", "aboutMe", "cooking", "free", "sailing", "paid", "public speaking", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Yanna", "Gonzales", "ygonzales@gmail.com", "qwerty", "http://thebikinibuilders.com/wp-content/uploads/2017/05/chest-arm-workout-graduated-320x180.jpg", "Fullerton", "CA", "92576", "aboutMe", "guitar", "free", "painting", "paid", "drawing", "free");
INSERT INTO Users (firstName, lastName, email, password, photo, city, state, zip, aboutMe, skill1, cost1, skill2, cost2, skill3, cost3) VALUES ("Larry", "Johnson", "ljohnson@gmail.com", "qwerty", "http://mapleleafadventures.com/wp-content/uploads/2015/11/161-DSC_9232-2-318x180.jpg?lbisphpreq=1", "Stanton", "CA", "92577", "aboutMe", "cooking", "free", "film", "paid", "photography", "free");


SELECT * FROM mentorMe_db.Users;